export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Portfolio } from './Portfolio';
export { default as Process } from './Process';
export { default as Services } from './Services';
export { default as TechStack } from './TechStack';
export { default as FAQ } from './FAQ';
export { default as Careers } from './Careers';
export { default as Contact } from './Contact';
